apiVersion: apps/v1
kind: Deployment
metadata:
  name: upg-loadme-deploy
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 10%
  replicas: 1
  selector:
    matchLabels:
      app: upg-loadme
  template:
    metadata:
      name: upg-loadme
      labels:
        app: upg-loadme
    spec:
      containers:
      - name: upg-loadme
        image: 764242751754.dkr.ecr.us-east-1.amazonaws.com/capstone-c42-deb:latest
        ports:
        - containerPort: 8081
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 1
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 1
          periodSeconds: 3
        resources:
          requests:
            memory: "500M"
            cpu: "200m" # This is important during Hpa autoscaling and downscaling
          limits:
            memory: "1Gi"
      tolerations:
        - key: test
          value: loadapp
          operator: Equal
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values:
                - capstone

---
apiVersion: v1
kind: Service
metadata:
  name: upg-loadme-c42
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8081
  selector:
    app: upg-loadme
